name: Create Branch on In Progress

on:
  projects_v2_item:
    types: [edited]

jobs:
  create-branch:
    if: github.event.repository.fork == false
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: read
      projects: write
    steps:
    - name: Check status change
      id: check_status
      uses: actions/github-script@v6
      with:
        script: |
          const { changes, projects_v2_item } = context.payload;
          const statusChange = changes.find(c => 
            c.field?.name === 'Status' && 
            c.field.data_type === 'single_select' &&
            c.field_value?.option_name === 'In Progress'
          );
          
          if (!statusChange) return core.setOutput('trigger', 'false');
          
          if (projects_v2_item.content_type !== 'Issue') {
            core.setOutput('trigger', 'false');
            return;
          }
          
          core.setOutput('trigger', 'true');

    - name: Get issue info
      if: steps.check_status.outputs.trigger == 'true'
      id: get_issue
      uses: actions/github-script@v6
      with:
        script: |
          const { content_node_id } = context.payload.projects_v2_item;
          const response = await github.graphql(`
            query ($nodeId: ID!) {
              node(id: $nodeId) {
                ... on Issue {
                  number
                  title
                  labels {
                    nodes {
                      name
                    }
                  }
                }
              }
            }
          `, { nodeId: content_node_id });
          
          core.setOutput('number', response.node.number);
          core.setOutput('title', response.node.title);
          core.setOutput('labels', response.node.labels.nodes.map(l => l.name).join(','));

    - name: Determine branch type
      if: steps.check_status.outputs.trigger == 'true'
      id: branch_type
      run: |
        if [[ "${{ steps.get_issue.outputs.labels }}" == *"documentation"* ]]; then
          echo "type=documentation" >> $GITHUB_OUTPUT
        elif [[ "${{ steps.get_issue.outputs.labels }}" == *"hotfix"* ]]; then
          echo "type=hotfix" >> $GITHUB_OUTPUT
        else
          echo "type=feature" >> $GITHUB_OUTPUT
        fi

    - name: Create branch name
      if: steps.check_status.outputs.trigger == 'true'
      id: branch_name
      run: |
        SANITIZED_TITLE=$(echo "${{ steps.get_issue.outputs.title }}" | tr '[:upper:]' '[:lower:]' | sed -e 's/[^a-z0-9]/-/g' -e 's/-\{2,\}/-/g' -e 's/^-//' -e 's/-$//')
        echo "name=${{ steps.branch_type.outputs.type }}/${{ steps.get_issue.outputs.number }}-${SANITIZED_TITLE}" >> $GITHUB_OUTPUT

    - name: Create branch
      if: steps.check_status.outputs.trigger == 'true'
      uses: peterjgrainger/action-create-branch@v2
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
      with:
        branch: ${{ steps.branch_name.outputs.name }}